### ISSUE TITLE
Bug: value of 0 for min throws an error

### ISSUE THREAD

**Issue by web-bert** [ashnur/random-number#1]
This check cannot rely on the falsy value:

https://github.com/ashnur/random-number/blob/master/index.js#L34

As it means that it uses options.min instead of the 0 passed in as min. I.e. if I create a generator with

``` JavaScript
var gen  = rn.generator( { min: 0, integer: true } );
```

and then try

``` JavaScript
var randomInt = gen( 0, 3 );
```

It throws this error:

``` bash
node_modules/random-number/index.js:16
    if ( max < min ) throw new Error('invalid options, max must be >= min')
```

**Comment by ashnur** [comment]
Thanks, will look into it.

**Comment by ashnur** [comment]
Turns out I had it fixed locally a long time ago, I just completely forgot to push it :(
